sudo: required
services:
  - docker

before_install:
  - docker build -t sarveshpanday/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sarveshpanday/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-658197536792"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master
