sudo: required
services:
  - docker

before_install:
  - docker build -t sarveshpanday/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sarveshpanday/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "docker-react"
  on:
    branch: master